config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "products#index"
  resources :products
  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order(:nama).page(params[:page]).per(params[:per])
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:nama, :kode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_application_header.html.erb
<header class="main-header">

  <!-- Logo -->
  <a href="<%= root_path %>" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>T</b>A</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Arta</b>Test</span>
  </a>

  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="/img/avatar5.png" class="user-image" alt="User Image">
            <span><%= current_user.email %><i class="caret"></i></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <img src="/img/avatar5.png" class="img-circle" alt="User Image">

              <p>
                <%= current_user.email %>
                <small>RoR Developer</small>
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="<%= edit_user_registration_path %>" class="btn btn-primary btn-flat">Edit Profile</a>
              </div>
              <div class="pull-right">
                <%= link_to signout_path, class: "btn btn-default btn-flat", title: "Sign out" do%>
                  Sign out
                <% end %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>

  </nav>
</header>

app/views/layouts/_application_sidebar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="/img/avatar5.png" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p><%= current_user.email %></p>
        <a href="#"><i class="fa fa-circle text-success"></i> <%= current_user.last_sign_in_ip.to_s %></a>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li><a href="<%= products_path %>"><i class="fa fa-archive"></i>Product</a></li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArtaTest</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'false' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'false' %>
    <%= csrf_meta_tags %>
    <!-- Font Awesome -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  	<!-- Ionicons -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  </head>

  <% if user_signed_in? %>
    <body class="hold-transition skin-blue sidebar-mini">
      <div class="wrapper">
        <%= render "layouts/application_header" %>
        <%= render "layouts/application_sidebar" %>
        <div class="content-wrapper">
          <!-- Content Header (Page header) -->
          <% flash.each do |name, msg| %>
            <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
              <%= msg %>	            
            <% end %>
          <% end %>
          <%= yield %>
        <!-- /.content -->
        </div>

        <footer class="main-footer">
          <div class="pull-right hidden-xs">
            <b>Version</b> 0.0.1
          </div>
          <strong>Copyright &copy; 2017 <a href="http://dijekarim.com">Dijekarim</a>.</strong> All rights reserved.
        </footer>
      </div>
    </body>
  <% else %>
    <body class="hold-transition login-page">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
          <%= msg %>	            
        <% end %>
      <% end %>
      <%= yield %>
    </body>
  <% end %>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <div class="box-body">
      <% if product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
          <% product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :nama, class: "control-label" %>
        <%= form.text_field :nama, id: :product_nama, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :kode, class: "control-label" %>
        <%= form.text_field :kode, id: :product_kode, class: "form-control" %>
      </div>
  </div>

  <div class="box-footer">
    <%= link_to 'Cancel', products_path, class: "btn btn-default" %>
    <%= form.submit 'Save', class: "btn btn-primary pull-right"  %>
  </div>
<% end %>

app/views/products/edit.html.erb
<section class="content-header">
  <h1> 
  &nbsp; Product <small> <%= params[:action] %> </small></h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Master Product</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="box">
        <%= render 'form', product: @product %>
      </div><!-- /.box -->
    </div>
  </div>
</section>

app/views/products/index.html.erb
<section class="content-header">
  <h1> 
  &nbsp; Product <small> List </small></h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Master Product</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="box">
        <div class="box-header with-border">
          <%= link_to new_product_path, class: "btn btn-sm btn-primary pull-right" do %>
            <span class="glyphicon glyphicon-plus"></span> Add Product
          <% end %>
        </div><!-- /.box-header -->
        <div class="box-body">
          <table class="table table-hover table-striped">
            <thead>
              <tr>
                <th with="10%">No.</th>
                <th>Nama</th>
                <th>Kode</th>
                <th colspan="3" style="text-align: center;">Action</th>
              </tr>
            </thead>

            <tbody>
            <% @products.each_with_index do |product, idx| %>
              <tr>
                <td><%= idx+1 %>. </td>
                <td><%= product.nama %></td>
                <td><%= product.kode %></td>
                <td style="text-align: center;"><%= link_to product, class: "btn btn-default btn-xs" do %><span class="glyphicon glyphicon-eye-open"></span> Show<% end %></td>
                <td style="text-align: center;"><%= link_to edit_product_path(product), class: "btn btn-default btn-xs" do %><span class="glyphicon glyphicon-edit"></span> Edit<% end %></td>
                <td style="text-align: center;"><%= link_to product, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" do %><span class="glyphicon glyphicon-trash"></span> Delete<% end %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
          <div align="right"><%= paginate @products %></div>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div>
  </div>
</section>

app/views/products/new.html.erb
<section class="content-header">
  <h1> 
  &nbsp; Product <small> <%= params[:action] %> </small></h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Master Product</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="box">
        <%= render 'form', product: @product %>
      </div><!-- /.box -->
    </div>
  </div>
</section>

app/views/products/show.html.erb
<section class="content-header">
  <h1> 
  &nbsp; Product <small> List </small></h1>
  <ol class="breadcrumb">
    <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Master Product</li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="box">
        <div class="box-body">
          <dl class="dl-horizontal">
            <dt>Kode Product:</dt>
            <dd><%= @product.kode %></dd>
            <dt>Nama:</dt>
            <dd><%= @product.nama %></dd>
          </dl>
        </div><!-- /.box-body -->
        <div class="box-footer">
          <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-warning pull-right" %>
          <%= link_to 'Back', products_path, class: "btn btn-default" %>
        </div>
      </div><!-- /.box -->
    </div>
  </div>
</section>